// v2-react-classless-login/src/App.js
import React, { useRef, useEffect } from "react";
import mainStyles from "./main.scss";

const App = () => {
  const mainRef = useRef();
  useEffect(() => {
    const setMinHeight = () => {
      if (!mainRef.current) return;
      mainRef.current.style.minHeight = `${window.innerHeight}px`;
    };
    setMinHeight();
    window.addEventListener("resize", setMinHeight);
    return () => {
      window.removeEventListener("resize", setMinHeight);
    };
  }, []);

  return (
    <main ref={mainRef}>
      <h1>Sign in</h1>
      <form>
        <input
          type="text"
          name="login"
          placeholder="Login"
          aria-label="Login"
          autoComplete="username"
          required
        />
        <input
          type="password"
          name="password"
          placeholder="Password"
          aria-label="Password"
          autoComplete="current-password"
          required
        />
        <fieldset>
          <label htmlFor="remember">
            <input type="checkbox" role="switch" id="remember" name="remember" />
            Remember me
          </label>
        </fieldset>
        <button type="submit">Login</button>
      </form>
    </main>
  );
};
export default App;

// v2-angular-classless-login/src/app/app.component.ts
import { Component, ElementRef, HostListener, Renderer2, inject, viewChild } from "@angular/core";

@Component({
  selector: "app-root",
  standalone: true,
  template: `
    <main #mainRef>
      <h1>Sign in</h1>

      <form>
        <input
          type="text"
          name="login"
          placeholder="Login"
          aria-label="Login"
          autocomplete="username"
          required
          ngModel
        />

        <input
          type="password"
          name="password"
          placeholder="Password"
          aria-label="Password"
          autocomplete="current-password"
          required
          ngModel
        />

        <fieldset>
          <label for="remember">
            <input type="checkbox" role="switch" id="remember" name="remember" />
            Remember me
          </label>
        </fieldset>

        <button type="submit">Login</button>
      </form>
    </main>
  `,
})
export class AppComponent {
  readonly #renderer = inject(Renderer2);
  readonly #mainRef = viewChild.required<ElementRef<HTMLElement>>("mainRef");

  @HostListener("window:resize")
  onResize(): void {
    const mainRef = this.#mainRef();
    if (!mainRef) return;
    this.#renderer.setStyle(mainRef, "min-height", `${window.innerHeight}px`);
  }
}
